package com.movocash.movo.utilities.analytics

object CustomEventNames {
    const val EVENT_SIGN_IN = "SIGN_IN"
    const val EVENT_WELCOME = "RECEIVES_WELCOME_PAGE"
    const val EVENT_JOIN_NOW = "JOIN_NOW"
    const val EVENT_CLICK_MOVO_PAY = "MOVO_PAY"
    const val EVENT_CLICK_CASH_CARD = "CASH_CARD"
    const val EVENT_CLICK_DEPOSIT_HUB = "DEPOSIT_HUB"
    const val EVENT_CLICK_DIGITAL_BANKING = "DIGITAL_BANKING"
    const val EVENT_FT_MP_SEND_MONEY = "SEND_MONEY"
    const val EVENT_CREATE_CASH_CARD = "CREATE_CASH_CARD"
    const val EVENT_RELOAD_CASH_CARD = "RELOAD_CASH_CARD"
    const val EVENT_ADD_PAYEE = "ADD_PAYEE"
    const val EVENT_ACCESS_DIRECT_DEPOSIT = "ACCESS_DIRECT_DEPOSIT"
    const val EVENT_CLICK_SIGN_UP_CONT = "CONTINUE_SIGN_UP"
    const val EVENT_CLICK_PROFILE_CONT = "CONTINUE_CREATE_PROFILE"
    const val EVENT_CLICK_ID_VER_CONT = "CONTINUE_ID_VERIFICATION"
    const val EVENT_COPY_CASH_CARD = "COPY_CASH_CARD"
    const val EVENT_CLICK_CASH_OUT_TO_BANK = "CASH_OUT_TO_BANK"
    const val EVENT_PRIMARY_MOVO_CASH_ACCOUNT_MAKE_PAYMENT = "PRIMARY_MOVO_CASH_ACCOUNT_MAKE_PAYMENT"
    const val EVENT_CASH_CARD_MAKE_PAYMENT = "CASH_CARD_MAKE_PAYMENT"
}